name: taesch
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  logger: ^1.1.0
  # location: ^3.0.0
  http:
  sqflite:
  sqlite3_flutter_libs:
  path:
  shared_preferences: ^2.0.15
  flutter_map: ^3.0.0
  latlong2: ^0.8.1 # <-- used in conjunction with flutter_map
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.1
  test:
  sqflite_common_ffi:
  app_settings: ^4.1.8

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppLogo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
