name: Docker Image CI

on:
  push:
    branches: [ "35-automatisches-testing" ]
  pull_request:
    branches: [ "35-automatisches-testing", "developer", "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build image in order to test the code
      run: docker build -t taesch_test:$(date +%s) ./taesch
